version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tsid-pg
    environment:
      POSTGRES_DB: membersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
